export const YEAR = '2021'
export const TITLE = 'The Small Book'
export const DESCRIPTION = 'Directory of small businesses providing high quality crafts and products.'
export const AUTHOR = 'Nina Armangué Braun'
export const URL = 'https://the-small-book.vercel.app'
export const CMS_NAME = 'Markdown'
export const HOME_OG_IMAGE_URL = 'https://the-small-book.vercel.app/images/banner.jpg'
